function EZSlots(id,useroptions){var that=this;var options=useroptions?useroptions:{};this.reelCount=options.reelCount?options.reelCount:3;this.symbols=options.symbols?options.symbols:['A','B','C'];this.sameSymbolsEachSlot=true;this.startingSet=options.startingSet;this.winningSet=options.winningSet;this.width=options.width?options.width:100;this.height=options.width?options.height:100;this.time=options.time?(options.time*1000):6500;this.howManySymbolsToAppend=Math.round(this.time/325);this.endingLocation=7;this.jqo=$("#"+id);this.jqoSliders=[];this.callback=options.callback;this.init=function(){this.jqo.addClass("ezslots");if(typeof this.symbols[0]!='string'){this.sameSymbolsEachSlot=false;}
for(var i=0;i<this.reelCount;i++){var jqoSlider=$('<div class="slider"></div>');var jqoWindow=$('<div class="window window_'+i+'"></div>');this.scaleJqo(jqoWindow).append(jqoSlider);this.jqo.append(jqoWindow);this.jqoSliders.push(jqoSlider);this.addSymbolsToStrip(jqoSlider,i,false,true);}};this.scaleJqo=function(jqo){jqo.css("height",this.height+"px").css("width",this.width+"%");return jqo;}
this.addSymbolsToStrip=function(jqoSlider,whichReel,shouldWin,isInitialCall){var symbolsToUse=that.sameSymbolsEachSlot?that.symbols:that.symbols[whichReel];var chosen=shouldWin?that.winningSet[whichReel]:Math.floor(Math.random()*symbolsToUse.length);for(var i=0;i<that.howManySymbolsToAppend;i++){var ctr=(i==that.endingLocation)?chosen:Math.floor(Math.random()*symbolsToUse.length);if(i==0&&isInitialCall&&that.startingSet){ctr=that.startingSet[whichReel];}
var jqoContent=$("<div class='content'>"+symbolsToUse[ctr]+"</div>");that.scaleJqo(jqoContent);var jqoSymbol=$("<div class='symbol'></div>");that.scaleJqo(jqoSymbol);jqoSymbol.append(jqoContent);jqoSlider.append(jqoSymbol);}
return chosen;}
this.spinOne=function(jqoSlider,whichReel,shouldWin){var heightBefore=parseInt(jqoSlider.css("height"),10);var chosen=that.addSymbolsToStrip(jqoSlider,whichReel,shouldWin);var marginTop=-(heightBefore+((that.endingLocation)*that.height));jqoSlider.stop(true,true).animate({"margin-top":marginTop+"px"},{'duration':that.time+Math.round(Math.random()*1000),'easing':"easeOutElastic"});return chosen;}
this.spinAll=function(shouldWin){var results=[];for(var i=0;i<that.reelCount;i++){results.push(that.spinOne(that.jqoSliders[i],i,shouldWin));}
if(that.callback){setTimeout(function(){that.callback(results);},that.time);}
return results;}
this.init();return{spin:function(){return that.spinAll();},win:function(){return that.spinAll(true);}}}